//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public DichVu()
        {
            this.ChiTietGoiMons = new HashSet<ChiTietGoiMon>();
        }
    
        public int MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public decimal DonGia { get; set; }
        public string PhanLoai { get; set; }
        public Nullable<int> TonKho { get; set; }
    
        public virtual ICollection<ChiTietGoiMon> ChiTietGoiMons { get; set; }
    }
}
