//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuNapTien
    {
        public int MaGiaoDich { get; set; }
        public int MaTaiKhoanKhach { get; set; }
        public int MaTaiKhoanNhanVien { get; set; }
        public decimal SoTienNap { get; set; }
        public Nullable<System.DateTime> ThoiGianNap { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
