//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayTram
    {
        public MayTram()
        {
            this.PhienChois = new HashSet<PhienChoi>();
        }
    
        public int MaMay { get; set; }
        public string TenMay { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public decimal GiaMoiGio { get; set; }
        public string LoaiMay { get; set; }
    
        public virtual ICollection<PhienChoi> PhienChois { get; set; }
    }
}
