//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int MaNhanVien { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public string HoTen { get; set; }
        public string ChucVu { get; set; }
        public string SoDienThoai { get; set; }
        public string CaLamViec { get; set; }
        public decimal MucLuong { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public string TrangThai { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
