//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhienChoi
    {
        public PhienChoi()
        {
            this.ChiTietGoiMons = new HashSet<ChiTietGoiMon>();
        }
    
        public int MaPhien { get; set; }
        public int MaMay { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<System.DateTime> GioBatDau { get; set; }
        public Nullable<System.DateTime> GioKetThuc { get; set; }
        public Nullable<decimal> TienGio { get; set; }
    
        public virtual ICollection<ChiTietGoiMon> ChiTietGoiMons { get; set; }
        public virtual MayTram MayTram { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
