//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemNet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTiemNetEntities1 : DbContext
    {
        public QuanLyTiemNetEntities1()
            : base("name=QuanLyTiemNetEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietGoiMon> ChiTietGoiMons { get; set; }
        public DbSet<DichVu> DichVus { get; set; }
        public DbSet<LichSuNapTien> LichSuNapTiens { get; set; }
        public DbSet<MayTram> MayTrams { get; set; }
        public DbSet<PhienChoi> PhienChois { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
    }
}
