//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.LichSuNapTiens = new HashSet<LichSuNapTien>();
            this.LichSuNapTiens1 = new HashSet<LichSuNapTien>();
            this.PhienChois = new HashSet<PhienChoi>();
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int MaTaiKhoan { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public int VaiTro { get; set; }
        public Nullable<decimal> SoDu { get; set; }
        public string HoTen { get; set; }
    
        public virtual ICollection<LichSuNapTien> LichSuNapTiens { get; set; }
        public virtual ICollection<LichSuNapTien> LichSuNapTiens1 { get; set; }
        public virtual ICollection<PhienChoi> PhienChois { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
